/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --config D:\Git Repos\VRCLUB-QuestDev\worker\wrangler.dev.jsonc D:\Git Repos\VRCLUB-QuestDev\worker\dev-env.d.ts` (hash: 3b5d486f178b0f169788517eb59ad6e9)
interface __BaseEnv_Env {
	DB: D1Database;
	ALLOWED_ORIGINS: "https://nocturnedev.mitwee.nl,https://nocturne-dev.pages.dev";
	APP_ORIGIN: "https://nocturnedev.mitwee.nl";
	ROOM_CAPACITY: "32";
	MEDIA_TRANSPORT: "sfu";
	SFU_APP_ID: "59da19e9bdf99111a7a1a6a3ee0d5dae";
	CLUB_ROOM: DurableObjectNamespace<import("./src/dev-index").ClubRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/dev-index");
		durableNamespaces: "ClubRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
